### ISSUE TITLE
Alternative Glide wrapper

### ISSUE THREAD

**Issue by bolrog** [fearedbliss/Cactus#1]
I saw you support ddraw and sven's glide wrapper, and detail some of the long-standing issues with the latter in your wiki. May I recommend my alternate Glide wrapper? It has fixes for the issues mentioned and adds a number of other enhancements such as true high frame rate and a built in resolution mod. I'd love to help if you want to include support for it.

https://www.github.com/bolrog/d2dx

**Comment by fearedbliss** [comment]
Hey @bolrog,

First I want to say thanks for the all the hard work you've put into the project! I took a look at it (And I've saw mentions of it over the past few months online as it was being developed). Unfortunately for various reasons I won't be including it in Cactus. I'll give an explanation below.

As explained in the main Cactus page, the focus of Cactus is to provide a centralize repo for all versions of Diablo II (in it's Vanilla state) and encourage people to play all of those versions (1.00 - 1.14d). Singling is my "non-gameplay modification" patchset that is a optional / opt-in and also reflects the vision of Cactus overall:

---

Singling does not provide any sort of modifications that have a psychological impact on the immersion aspect of Vanilla Diablo II, which eliminates all visual level changes as a result. For example, Extended Stash (10x10), Font Fix, and Item Level don't really have any gameplay impact, however they do have a psychological impact on the immersion of the user's experience. Since my goal with Cactus and Singling is to allow people to enjoy any version of Diablo II that ever came out while adhearing to the original spirit of the game, modifications outside of this goal are not included.

---

From what I saw in D2DX, it includes a custom resolution mod that allows the increase of the internal resolution. I don't support these types of modifications to the game (And I don't provide an easily accessible option to these types of alterations on purpose - I do know there was a `-dxnoresmod` for earlier versions where it used SlashDiablo's mod rather than the newer one).

D2DX also only supports a very limited number of versions of the game while I support all versions of the game for Cactus (including the renderers). Only Singling has support for select versions of the game primarily because I wanted to focus on particular moments of significant relevant in the development of the game. Thus Singling supports: 1.00, 1.05b, 1.07, 1.08, 1.09b, and 1.13d.

I've been planning on removing `glidewrapper` completely from the project since I only included it for 1.14d (Due to them removing ddraw support) and I promote the usage of `cnc-ddraw` for all versions of the game before `1.14d`. D2 Resurrected is based on `1.14d` so my Singling patchset in Cactus doesn't support that version at all. Also `perspective` mode isn't enough of a feature for me to justify its usage.

Lastly, I tend to avoid projects that are GPL licensed. `cnc-ddraw` is MIT and works across all versions of the game. However I do know that inclusion of this project won't impact Cactus in any way since it's independent and I'm not linking to it or using any of its source code. My previously forked PlugY version `Alpaca` was actually GPLv3 as well (Which I do not like at all and if anything I agree with Linus' on continued usage of GPLv2-Only - However this is a discussion not important to be had here), and I actually ended up completely removing `Alpaca`'s availability from my github for various reasons, one of them being because Yohann required GPLv3 which is really demotivating for me to continue developing a fork based on the license, so I preferred to just shut down the whole thing after a years of developing on it. `Alpaca` can still be found online if you know where to look, but I'm not promoting it or making it available anymore.

As I said in the beginning of the article, I really do appreciate your hard work on this project and I feel it will benefit most of the D2 users (Since most people are playing the newer versions anyways, I'm just more of an oddball and actually switched to playing older versions like `1.05b` and `1.09b` as my primary versions and time traveling in general).

Keep up the good work,

- Jonathan
