### ISSUE TITLE
Empty error message when launching versions other than 1.14d

### ISSUE THREAD

**Issue by achim-t** [fearedbliss/Cactus#1]
I installed Cactus in 1.14d, running other versions only gets me an empty error message. 

![capture](https://user-images.githubusercontent.com/11352910/40377419-2ea0bca4-5df1-11e8-83ba-0d8320f15b69.PNG)

("Fehler" is German for "error")

**Comment by fearedbliss** [comment]
This doesn't seem like a Cactus issue if anything it seems like you installed your Diablo game with the latest 1.14 installer and are going backwards. Blizzard changes the MPQ format a bit and this will cause similar errors. You should either watch my video that explains this issue and teaches you how to fix it, or use my Singling mod that includes the fix 

https://youtu.be/tz1J4FyuBHE
https://github.com/fearedbliss/singling

You can also reinstall the game with 1.03 to 1.07 ISOs

**Comment by achim-t** [comment]
You were right. I managed to run an older version after editing the mpqs. 

When running the older version, though, it loops through ascii characters in the upper left corner of my screen multiple times. IIRC this has something to do with glide? I'm not sure why this would only happen for the older version, the originally installed version doesn't have this problem. 

Can you help me with that?

**Comment by fearedbliss** [comment]
Those are related to graphical issues related to the game and the way it interacts with Windows Aero on Windows 7. You can disable desktop composition if you are on Windows 7 or switch to Windows Classic or Non Aero equivalent. Also if you never ran a version before 1.14, you will need to run the D2VidTst and select either Direct 3D or Glide. 1.14 removed this test and defaults to D3D

**Comment by achim-t** [comment]
I'm on Windows 10.

Nothing happens when I try to run D2VidTst, not even as Admin. Also, I use the -3dfx flag, shouldn't that work either way?

**Comment by fearedbliss** [comment]
You need to run d2vidtst with it being in the d2 root folder since that contains the MPQs. Make sure to run this afternoon you fixed all of your DLLs so they are compatible. Im also on Windows 10 as well with glide for all versions from 1.00 to 1.14. 

I'm not sure if you watched my recent video but it might help you set everything up
https://youtu.be/wgzJww-dzwY

**Comment by fearedbliss** [comment]
If it's looping through the characters then that's definitely a graphical issue. Are you sure glidewrapper is installed and working?

glide-init.exe and glide3x.dll or w/e the dll is called should be in your d2 root directory, and then you would run the game with -3dfx. If you open glide-init.exe, you should be able able to run a test launch as well that will show you what the glide window will look like. If all the appropriate files are correct, this should work.

Due note, as stated in the README/README-MORE, Cactus considers the d2 root folder as a replaceable directory since when you switch versions it deletes all of the required files for that version, and then copies the new ones from the storage directory. So make sure that when you want to install dlls, you switch to another version, replace the files in the storage directory for w/e version you want to run, and then switch back to that version.

**Comment by fearedbliss** [comment]
Also try running everything in window mode first and then work your way up to full screen if that's what you want. You can do -w, and also set glide-init to "Window mode" as well.

I also noticed in your screenshot you put "-data -txt", it's "-direct -txt".

**Comment by achim-t** [comment]
Glidewrapper is installed and working for 1.14d (I have it show me the clock and FPS) in fullscreen.
It doesn't work for 1.13d. 

I just discovered that I can run in fullscreen without glide, all my attempts so far included -3dfx. Without that flag, it takes a bit when loading a character or exiting, but I think that I can live with that.

Thanks for your help.

**Comment by fearedbliss** [comment]
That's weird. In the video I sent you, I demonstrate basically all versions from 1.00 to 1.14 working with glide. When you have more time I suppose you can keep messing with it ;). Closing.
