### ISSUE TITLE
After clicking Add Cactus closes and does not save 

### ISSUE THREAD

**Issue by TickleFairy** [fearedbliss/Cactus#12]
So I am attempting to follow your video using the current version listed. Using any version for Path, using directory as such, and -w. When clicking add cactus closed out and when reopening it does not save anything listed.

**Comment by fearedbliss** [comment]
There isn’t an issue with the code, since there hasn’t been a release for several years and many players use it but have not filed any bug reports, so I’m fairly confident that it is a problem on your end.

I would say make sure that the directory you are running cactus from has read and write permissions since if there is a permission problem on the file system, the program won’t be able to write. You can also try re opening the application in administrator mode, is that works then there is a definitely a permission issue.
