### ISSUE TITLE
Cannot switch between 1.14d and older versions (Succulent) without deleting registry files.

### ISSUE THREAD

**Issue by Beepu** [fearedbliss/Cactus#19]
I can get either 1.14d or Succulent (1.13d) to work, but trying to switch between them causes an error unless I delete the VideoConfig registry key, as specified in the RENDERERS README.

I'm using the recommended renderers for both 1.14d (glidewrapper) and Succulent (cnc -ddraw), I'm using them because it won't boot in fullscreen otherwise.

My technical knowledge is pretty limited, but it appears that glidewrapper overwrites the renderer key in the registry, causing problems when I try to play the Succulent platform.

**Comment by fearedbliss** [comment]
I cannot reproduce this and can switch between 1.13d w/ `cnc-ddraw` and 1.14d with `glidewrapper` perfectly fine. The glidewrapper configuration does not modify the `HKEY_CURRENT_USER\SOFTWARE\Blizzard Entertainment\Diablo II\VideoConfig` path. The only thing that would modify that is the 1.13d `D2VidTst.exe` since that's the purpose of that automatic video configuration tool. Please follow the instructions on how to install/delete that folder and configuring it properly.

In terms of 1.14d, make sure to have the `-3dfx` flag set. For 1.13d, the Render flag should be set to 0 as documented in the RENDERER documentation.

**Comment by Beepu** [comment]
This was almost certainly user error, once I uninstalled and reinstalled everything, it worked perfectly. I did have to manually set the registry VideoConfig key to 0, but that might have been an earlier mistake, and once that was done everything functioned exactly as it should.

**Comment by fearedbliss** [comment]
Glad to hear.
