### ISSUE TITLE
cnc-ddraw for 1.14b

### ISSUE THREAD

**Issue by FunkyFr3sh** [fearedbliss/Cactus#2]
I made cnc-ddraw working with 1.14b, maybe it's useful for you.

Rename SmackW32.dll to SmackW32x.dll and then place the custom SmackW32.dll into your game folder and now cnc-ddraw will work fine with 1.14b.

[1.14b-cnc-ddraw.zip](https://github.com/fearedbliss/Cactus/files/6751753/1.14b-cnc-ddraw.zip)

**Comment by fearedbliss** [comment]
Hey @FunkyFr3sh,

Thanks for this. Although I'm not supporting 1.14+ anymore (I'm including the files since it's an official version but I'm not providing any official video support). Given that Blizzard officially removed official ddraw support for 1.14, and D2:R is coming out which is based on 1.14, I'm not interested in maintaining support for bringing back that type of video support (Although I did know that some people mentioned that ddraw could be re-activated which from looking at the source you provided, that's what you did!).

I would suggest probably posting this up on PhrozenKeep though, I think other people would definitely be interested in this.

fearedbliss
