### ISSUE TITLE
Why not use symlinks/hardlinks?

### ISSUE THREAD

**Issue by Ark-kun** [fearedbliss/Cactus#3]
You may just symlink/hardlink/junction all heavy files like MPQs and have compact, but flawlessly working mods.

**Comment by fearedbliss** [comment]
Yup I thought about this but decided not to go with that implementation since I wanted a cleaner solution that worked completely within the root directory (Using root directory as basically a RO location but keeping actual critical files in their own separate platforms). There are many ways to implement a version switcher, this is just my preferred way of doing it.
