### ISSUE TITLE
Screen flickering on desktop when Cactus windows is on screen [GSync related]

### ISSUE THREAD

**Issue by jaydee2k** [fearedbliss/Cactus#3]
When the Cactus window is on screen the windows desktop is constantly changing its brightness during mouse movement.
Turning off GSync fixes the issue. It's the only programm I know with that behaviour.

**Comment by fearedbliss** [comment]
Weird, I've never experience that and there isn't anything special that Cactus is doing. It's a standard Windows .NET (WPF/XAML) based application. I don't notice any weirdness on my Razer laptop that has a Optimus (w/ an NVIDIA RTX 2060) card. Are there any repro steps that you have? Steps to enable g-sync, and the exact workflow you use to open Cactus. Also do you just open Cactus (and not Diablo) and just leaving Cactus open without doing anything, does it still occur? For the record, I've tried Cactus on Windows XP, Windows 7, and Windows 10 over the years and never had that behavior (but those machines probably didn't have g-sync). Regardless, since I said before that this is just a standard Windows .NET App, I would imagine that other .NET (WPF/XAML) based applications may have that issue and the problem would be with either NVIDIA or Microsoft.

**Comment by fearedbliss** [comment]
I just remembered, there may have been some situations where I noticed everything flicker but it usually was because of some video problems (Particularly with D2). Are you using glidewrapper? I've been recommending people to stop using it and switch to cnc-ddraw. Also make sure you have the latest nvidia driver installed. I remember when It was flickering it may have been on a fresh install of Windows 10 where the proper nvidia drivers weren't installed, thus the game ran in software rendering mode and caused a bunch of flickering. But yea I probably can't help with this since I'm 99/100% confident it isn't Cactus.

**Comment by jaydee2k** [comment]
Yeah I'm thinking now its a windows/nvidia issue too. To be clear I have no flicker ingame. The flicker only appears on windows desktop when cactus is open and only if I activate Gsync for fullscreen and windowed applications in nvidia control panel.
When I switch to fullscreen only for Gsync there isn't any flicker anymore.
Only strange thing is that I have no app that causes the same flickering but this must be a coincidence then.

Ingame I'm using D2DX and its pretty damn good. Better than Svens wrapper by a mile. Can't play Diablo without them nice colour effects. :) I'm using cnc-ddraw for pre LOD only. Both are running flawless with cactus closed or running in the background.

Before I forgett, thanks for creating this awesome time machine!

**Comment by fearedbliss** [comment]
@jaydee2k That sounds good! And np about creating Cactus. Given that I usually play versions before 1.11 (Primarily: 1.05b, 1.09b, 1.10, but 1.07 is in my list to seriously try out eventually) myself almost exclusively (Although D2:R is 1.14d based so I have no choice for that), Cactus is invaluable for me haha, but also I use it to develop Singling as well since Singling patches like 6 versions <3.
