### ISSUE TITLE
Colors seem slightly off when using cnc-ddraw

### ISSUE THREAD

**Issue by Question2** [fearedbliss/Cactus#5]
I followed the instructions to setup cnc-ddraw and it works. The instructions says to test with alt+enter but i found out this does nothing if you run it with "fullscreen=true". The .ini is working at least however (running it with fullscreen=false causes the game to run in a window).

But the colors in the game seem faded (at least compared to running the game with a 3dfx glide wrapper). As an example : 

![image](https://user-images.githubusercontent.com/1191378/132619833-28a687db-bbf3-45f2-b0d8-46790eaaefbc.png)

The gold text used by rare items is noticeably faded compared to when running the game via a 3df xglide wrapper : 

![diablo 2-2](https://user-images.githubusercontent.com/1191378/132620308-8e82e3a5-edb8-405f-91ec-f3c782c64b6b.png)

Is this normal?

Edit : I cant turn perspective mode on either. Is that normal?

**Comment by fearedbliss** [comment]
Hey, if you believe there are any bugs, you should report it to cnc-ddraw directly (https://github.com/CnCNet/cnc-ddraw).

As for your other questions, this seems to be the way that cnc-ddraw is designed (in respect to what happens if you have both fullscreen and window set to true). One of them would have to take precedence so that makes sense. However if you want to run with both full screen and window mode, you could use the default set up that I have where it starts in a window, but if you press [alt + enter], it will go into full screen mode and will remember as well. You probably might also have fullscreen set to true, and maybe window false? I haven't tested it but I wouldn't be surprised if one option is true and one is false it would let you alternate.

As for the colors, I would say that is subjective. For me, I interpret them very similar to how glidewrapper has it, but if you're interpreting it differently, you may want to try out different shaders. I wrote a little bit about that here: https://github.com/fearedbliss/Cactus/blob/master/README-RENDERERS.md#tweaking-cnc-ddraw

Perspective mode is a glide option. cnc-ddraw is a directdraw implementation so it is a completely different technology. D2 has three modes (pre 1.14): directdraw, direct 3d, and glide.

I'm closing this since this isn't really a Cactus issue.
