### ISSUE TITLE
Error 25: A critical error has occured while initializing Direct3D

### ISSUE THREAD

**Issue by Draagoo** [fearedbliss/Cactus#6]
This just doesn't work. I'm trying to run 1.13c and my version is 1.14. I pasted all of cactus in the diablo root folder and set the platform to 1.13c and the path as my diablo "game.exe". However all I get is the window pops up, instantly closes and I get error 25. I also did the regedit thing where you make a Dword called "render"

**Comment by fearedbliss** [comment]
That seems to be an issue with your environment. I've provided a good amount of documentation on setting this up and also recorded a video on setting up the entire process. Outside of that, you'll need to do some local debugging since there could be any number of reasons why it is messing up locally.

**Comment by vanam** [comment]
Adding '-w' flag helped in my case.
