### ISSUE TITLE
Support for additional patches (e.g. 1.08) in Singling

### ISSUE THREAD

**Issue by automorphism88** [fearedbliss/Cactus#7]
Is there any chance you would consider adding support for additional patches in Singling? I read the [readme](https://github.com/fearedbliss/Cactus/blob/master/README-SINGLING.md#patch-rational) where you list the rationale for which patches are included, and while I appreciate you may not want to include all patches when there is no reason to play most of them, there are a few which people do play but are not included. In chronological order, the patches which I think it would be useful to add, along with rationales for their inclusion, are:

1. 1.08 - Rare jewels with 6 affixes, pre-1.09 versions of unrackable uniques that can't drop in 1.07 (e.g. Windforce), access to crafting recipes that are disabled in 1.07, higher chance of racking uniques. Many disadvantages, like broken MF, but that's what makes playing old patches interesting.
2. 1.09d - The broken CTC can be desirable, e.g. for safer use of Oculus on a sorceress.
3. 1.10a/s - Beta versions of items (BKWB, CTA, etc.) which were nerfed in the final 1.10 release
- Honorable mention: 1.06b, because while your logic for including 1.05b instead makes perfect sense, it seems like a lot more people play 1.06b, simply because it's the last pre-LOD version.

**Comment by fearedbliss** [comment]
Since I have to do this work manually and maintain it, I'm opposed to adding versions I don't really think add critical parts to the game. For singling it's focusing on particular patches I think are pivotal moments in the life time of the game. Cactus includes all the versions of Diablo III in a vanilla form (excluding the removal of securom so you can play without the CD). But any additional enhancements that I made for Singling, will only be limited to the patches I support.
