### ISSUE TITLE
Linux: "entry point" error

### ISSUE THREAD

**Issue by nesingho** [fearedbliss/Cactus#8]
After step 3. run cactus.exe via wine I get the error:

`The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

- installed D2 version is 1.13c
- D2SE is currently installed parallel (for the first test) -> can they conflict?
- PlugY 11.02 is installed
- Linux kernel is 5.2
- GFX is glide (runs with Vanilla and D2SE without problems)

What I have done:

1. copied files into D2 root directory
2. ran FIX_MPQS_RUN_AS_ADMIN.bat via wine without errors

Thx for tipps.

**Comment by fearedbliss** [comment]
D2SE and Cactus probably would conflict. Although I haven't tested since Cactus is an independent application and there is no interest in maintaining D2SE compatibility. Also Cactus is a Windows only application so Linux is unsupported (I do personally use Debian on all of my systems except my gaming desktop which is Windows).
